//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieCrudApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int movie_id { get; set; }
        public string movie_name { get; set; }
        public string movie_language { get; set; }
        public Nullable<int> movie_rating { get; set; }
    }
}
